### ISSUE TITLE
Movement functions

### ISSUE THREAD

**Issue by nepster-web** [bupy7/doctrine-nested-set#2]
Hello.
When do you plan to implement movement functions:

- Moving item after some item.
- Moving item before some item.
- Making as root item.
- Making as a child item of some parent item.

???

**Comment by bupy7** [comment]
Hi! Not soon, sorry.  =(

**Comment by nepster-web** [comment]
Ok, if I can, I will try to help. Do you will have time to check my pull requests?

**Comment by bupy7** [comment]
Of course, I will attempt to check your pull-request as soon as possible. By the way, don't forget about tests.

**Comment by nepster-web** [comment]
okay, thank you.
